# Generated by Django 5.2.2 on 2025-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anime_likes_alter_anime_title_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
