# Generated by Django 5.2.2 on 2025-06-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_anime_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='views',
        ),
    ]
